## Numpy

In [1]:
###### 62 ###########

In [2]:
import numpy as np

## DataTyoes & Attributes

In [3]:
# numpy's main data type is ndarray
a1 = np.array([1,2,3,])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2, 3.4], [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [
              [10, 11, 12], [13, 14, 15], [16, 17, 18]]])


In [6]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
# create a datafrom from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.0  6.5

In [15]:
############# 63 ################3

## 2. How we can create numpy array

In [16]:
sample_array = np.array([1, 2, 3])
sample_array


array([1, 2, 3])

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
zeros = np.zeros((1,2))
zeros

array([[0., 0.]])

In [19]:
range_array = np.arange(1,10,2)
range_array

array([1, 3, 5, 7, 9])

In [20]:
random_array = np.random.randint(1,10,size=(3,5))
random_array


array([[2, 6, 1, 4, 7],
       [7, 7, 4, 3, 7],
       [5, 9, 2, 1, 4]])

In [21]:
random_Array2 = np.random.random((5,3))
random_Array2

array([[3.73216947e-02, 9.77615117e-01, 9.32850587e-02],
       [8.61719325e-04, 3.63162448e-01, 8.92099940e-01],
       [6.32488433e-01, 7.74736984e-01, 6.88308183e-01],
       [5.93199093e-01, 6.35680179e-01, 5.71190390e-01],
       [6.51575064e-01, 1.16035240e-02, 4.52445366e-01]])

In [22]:
random_Array3 = np.random.rand(5, 3)
random_Array3

array([[0.06871215, 0.86200582, 0.40334211],
       [0.82066162, 0.33256841, 0.95999616],
       [0.18549816, 0.57375914, 0.16539959],
       [0.44822502, 0.7523533 , 0.77465841],
       [0.73256504, 0.91091631, 0.73049709]])

In [23]:
####### 64 ######

In [24]:
# Pseudo-random numbers
np.random.seed(seed=0)
# the randomarray4 will seed with zero so it will not change.
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [25]:
############### 65 ###########

## 3. Viewing arrays and matrics

In [26]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a1

array([1, 2, 3])

In [28]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
# get the first 2 number of the inner most array
a3[:, :, :2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

In [31]:
################## 66 ###############

## 4.Manipulating and comparing arrays

### Arithmetic

In [32]:
a1

array([1, 2, 3])

In [33]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [34]:
a1 + ones

array([2., 3., 4.])

In [35]:
a1 - ones

array([0., 1., 2.])

In [36]:
a1 * ones

array([1., 2., 3.])

In [37]:
a1

array([1, 2, 3])

In [38]:
a2

array([[1. , 2. , 3.4],
       [4. , 5. , 6.5]])

In [39]:
a1 * a2

array([[ 1. ,  4. , 10.2],
       [ 4. , 10. , 19.5]])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
# How can you reshape a2 to be compatible with a3?


a2* a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
##### 67 ###########

### Aggregation

In [ ]:
list_list = [1, 2, 3, 4]
sum(list_list)

10

In [ ]:
np.sum(a1)

6

Use python's methods (`sum()`) on python datatypes and use Numpy's methods on Numpy Arrays (`np.sum()`)

In [ ]:
# Create massive numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [ ]:
%timeit sum(massive_array)  # python method
%timeit np.sum(massive_array) # numpy method

5.65 ms ± 137 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
30.8 µs ± 455 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
np.std(a2)

1.8200274723201295

In [42]:
np.var(a2)

3.3125